name = "MathProgBenchmarks"
uuid = "f7f8d0a1-fd34-491e-a7ac-a4cf52f91fe5"
version = "0.1.0"
authors = ["Guillaume Dalle"]

[workspace]
projects = ["test"]

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
QPSReader = "10f199a5-22af-520b-b891-7ce84a7b1bd0"

[compat]
DataDeps = "0.7.13"
GZip = "0.6.2"
Logging = "1.11.0"
QPSReader = "0.2.1"
julia = "1.10"
